<?php

/**
 * Practical ISO currency catalog for company Application Settings.
 * code => [name, symbol]
 */
return [
    'AED' => ['name' => 'UAE Dirham', 'symbol' => 'AED'],
    'USD' => ['name' => 'US Dollar', 'symbol' => '$'],
    'EUR' => ['name' => 'Euro', 'symbol' => '€'],
    'GBP' => ['name' => 'British Pound', 'symbol' => '£'],
    'SAR' => ['name' => 'Saudi Riyal', 'symbol' => 'SAR'],
    'QAR' => ['name' => 'Qatari Riyal', 'symbol' => 'QAR'],
    'KWD' => ['name' => 'Kuwaiti Dinar', 'symbol' => 'KWD'],
    'BHD' => ['name' => 'Bahraini Dinar', 'symbol' => 'BHD'],
    'OMR' => ['name' => 'Omani Rial', 'symbol' => 'OMR'],
    'PKR' => ['name' => 'Pakistani Rupee', 'symbol' => 'Rs'],
    'INR' => ['name' => 'Indian Rupee', 'symbol' => '₹'],
    'JPY' => ['name' => 'Japanese Yen', 'symbol' => '¥'],
    'CNY' => ['name' => 'Chinese Yuan', 'symbol' => '¥'],
    'CAD' => ['name' => 'Canadian Dollar', 'symbol' => 'CA$'],
    'AUD' => ['name' => 'Australian Dollar', 'symbol' => 'A$'],
    'CHF' => ['name' => 'Swiss Franc', 'symbol' => 'CHF'],
    'TRY' => ['name' => 'Turkish Lira', 'symbol' => '₺'],
    'EGP' => ['name' => 'Egyptian Pound', 'symbol' => 'E£'],
    'JOD' => ['name' => 'Jordanian Dinar', 'symbol' => 'JOD'],
    'LBP' => ['name' => 'Lebanese Pound', 'symbol' => 'L£'],
    'MAD' => ['name' => 'Moroccan Dirham', 'symbol' => 'MAD'],
    'SGD' => ['name' => 'Singapore Dollar', 'symbol' => 'S$'],
    'HKD' => ['name' => 'Hong Kong Dollar', 'symbol' => 'HK$'],
    'NZD' => ['name' => 'New Zealand Dollar', 'symbol' => 'NZ$'],
    'ZAR' => ['name' => 'South African Rand', 'symbol' => 'R'],
    'BRL' => ['name' => 'Brazilian Real', 'symbol' => 'R$'],
    'MXN' => ['name' => 'Mexican Peso', 'symbol' => 'MX$'],
    'PHP' => ['name' => 'Philippine Peso', 'symbol' => '₱'],
    'THB' => ['name' => 'Thai Baht', 'symbol' => '฿'],
    'MYR' => ['name' => 'Malaysian Ringgit', 'symbol' => 'RM'],
    'IDR' => ['name' => 'Indonesian Rupiah', 'symbol' => 'Rp'],
    'KRW' => ['name' => 'South Korean Won', 'symbol' => '₩'],
    'RUB' => ['name' => 'Russian Ruble', 'symbol' => '₽'],
    'SEK' => ['name' => 'Swedish Krona', 'symbol' => 'kr'],
    'NOK' => ['name' => 'Norwegian Krone', 'symbol' => 'kr'],
    'DKK' => ['name' => 'Danish Krone', 'symbol' => 'kr'],
    'PLN' => ['name' => 'Polish Zloty', 'symbol' => 'zł'],
    'CZK' => ['name' => 'Czech Koruna', 'symbol' => 'Kč'],
    'HUF' => ['name' => 'Hungarian Forint', 'symbol' => 'Ft'],
    'ILS' => ['name' => 'Israeli Shekel', 'symbol' => '₪'],
    'NGN' => ['name' => 'Nigerian Naira', 'symbol' => '₦'],
    'KES' => ['name' => 'Kenyan Shilling', 'symbol' => 'KSh'],
    'BDT' => ['name' => 'Bangladeshi Taka', 'symbol' => '৳'],
    'LKR' => ['name' => 'Sri Lankan Rupee', 'symbol' => 'Rs'],
    'NPR' => ['name' => 'Nepalese Rupee', 'symbol' => 'Rs'],
    'AFN' => ['name' => 'Afghan Afghani', 'symbol' => '؋'],
    'IQD' => ['name' => 'Iraqi Dinar', 'symbol' => 'IQD'],
    'IRR' => ['name' => 'Iranian Rial', 'symbol' => 'IRR'],
];
