<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Default ERP menu labels (sidebar / menu bar)
    |--------------------------------------------------------------------------
    | Keys must match the identifiers used in layouts.menu. Editable from Settings.
    */
    'defaults' => [
        'dashboard'            => 'Dashboard',
        'recycle_bin'         => 'Recycle Bin',
        'cash_banks'           => 'Cash & Banks',
        'loans'                => 'Bank Loans',
        'loans_list'           => 'Loans',
        'loans_upcoming_installments' => 'Upcoming Installments',
        'employees'            => 'Employees',
        'attendance'           => 'Attendance',
        'attendance_records'   => 'Attendance Report',
        'attendance_summary'   => 'Attendance',
        'items'                => 'Items',
        'items_list'           => 'Items List',
        'garage_items'         => 'Garage Items',
        'leads'                => 'Leads',
        'customers'            => 'Customers',
        'customer_list'        => 'customer list',
        'customer_invoices'    => 'Invoices',
        'customer_receipts'    => 'Payments Received',
        'receipts'             => 'Receipts',
        'payments'             => 'Payments',
        'vendors'              => 'Vendors',
        'recruiters'           => 'Recruiters',
        'riders'               => 'Riders',
        'riders_list'          => 'Riders List',
        'invoices'             => 'Invoices',
        'rider_invoice_templates' => 'Rider Invoice Templates',
        'activities'           => 'Activities',
        'live_activities'      => 'Live Activities',
        'rider_report'         => 'Rider Report',
        'rider_inventory'      => 'Rider Inventory',
        'rider_inventory_items' => 'Rider Inventory Items',
        'bikes'                => 'Bikes',
        'bike_list'            => 'Bike List',
        'bike_registration'    => 'Bike Registration',
        'bike_on_rent'         => 'Bike on rent',
        'bike_rent_customers'  => 'Customers',
        'maintenance'          => 'Maintenance',
        'maintenance_overview' => 'Maintenance',
        'cheques'              => 'Cheques',
        'sims'                 => 'Sims',
        'sim_companies'        => 'SIM Companies',
        'sim_payments'         => 'Payments Sent',
        'fuel_cards'           => 'Fuel Cards',
        'fuel_card_list'       => 'Card List',
        'fuel_data'            => 'Fuel Transactions',
        'fuel_companies'       => 'Fuel Companies',
        'rta_fines'            => 'RTA Fine',
        'rta_fines_unpaid'     => 'Unpaid',
        'rta_fines_paid'       => 'Paid',
        'rta_fines_tickets'    => 'Unpaid',
        'rta_saliks'           => 'RTA Saliks',
        'inventory'            => 'Inventory',
        'visa_expense'         => 'Visa Expense',
        'installments'         => 'Installments',
        'license_expense'      => 'License Expense',
        'legal_case'           => 'Legal Case',
        'passport_handover'    => 'Passport Handover',
        'visa_status_types'    => 'Visa Status Types',
        'expenses'             => 'Expenses',
        'vat'                  => 'VAT',
        'leasing_companies'    => 'Leasing Companies',
        'leasing_companies_list' => 'Leasing Companies List',
        'leasing_invoices'     => 'Invoices',
        'leasing_billing_invoice' => 'Billing Invoice',
        'leasing_receipt'      => 'Payments Received',
        'leasing_payment'      => 'Payments Sent',
        'garages'              => 'Garages',
        'garage_list'          => 'Garage List',
        'garage_customers'     => 'Garage Customers',
        'bike_rent_customer_receipts' => 'Payments Received',
        'supplier'             => 'Supplier',
        'suppliers'            => 'Suppliers List',
        'supplier_invoices'    => 'Supplier Invoices',
        'supplier_orders'      => 'Purchase Orders',
        'supplier_payments'    => 'Payments Sent',
        'assets'               => 'Assets',
        'agreements'           => 'Agreements',
        'documents'            => 'Documents',
        'vouchers'             => 'Vouchers',
        'accounts'             => 'Accounts',
        'chart_of_accounts'    => 'Chart Of Accounts',
        'ledger'               => 'Ledger',
        'vat_ledger'           => 'VAT',
        'vat_return_file'      => 'Return',
        'user_management'      => 'User Management',
        'users'                => 'Users',
        'roles'                => 'Roles',
        'permissions'          => 'Permissions',
        'activity_logs'       => 'Activity Logs',
        'company_settings'   => 'Company Settings',
        'settings'           => 'Settings',
        'erp_settings'       => 'ERP Settings',
        // Settings panel module labels (rename in each module's settings page)
        'rider_settings'     => 'Rider Settings',
        'employee_settings'  => 'Employee Settings',
        'bike_settings'      => 'Bike Settings',
        'voucher_settings'   => 'Voucher Settings',
        'vat_settings'       => 'VAT Settings',
        'account_fields'     => 'Account Fields',
    ],
];
