<?php

/**
 * Default Tabler icon classes for ERP sidebar modules (without "ti " prefix).
 * Keys match menu_labels.defaults and layouts.menu module keys.
 */
return [
    'defaults' => [
        'dashboard' => 'ti-layout-dashboard',
        'recycle_bin' => 'ti-trash',
        'cash_banks' => 'ti-building-bank',
        'loans' => 'ti-currency-dollar',
        'loans_list' => 'ti-list-details',
        'loans_upcoming_installments' => 'ti-calendar-event',
        'employees' => 'ti-user',
        'attendance' => 'ti-calendar-check',
        'attendance_records' => 'ti-calendar-check',
        'attendance_summary' => 'ti-calendar-stats',
        'items' => 'ti-notes',
        'items_list' => 'ti-list-details',
        'garage_items' => 'ti-tools',
        'leads' => 'ti-user-plus',
        'customers' => 'ti-user-star',
        'customer_list' => 'ti-users',
        'customer_invoices' => 'ti-receipt',
        'customer_receipts' => 'ti-receipt',
        'receipts' => 'ti-receipt',
        'payments' => 'ti-cash',
        'vendors' => 'ti-user-star',
        'recruiters' => 'ti-user-star',
        'riders' => 'ti-user-pin',
        'riders_list' => 'ti-users',
        'invoices' => 'ti-file',
        'activities' => 'ti-bike',
        'live_activities' => 'ti-activity',
        'rider_report' => 'ti-chart-bar',
        'rider_inventory' => 'ti-package',
        'rider_inventory_items' => 'ti-list-details',
        'bikes' => 'ti-motorbike',
        'bike_list' => 'ti-motorbike',
        'bike_registration' => 'ti-id',
        'bike_on_rent' => 'ti-motorbike',
        'bike_rent_customers' => 'ti-users',
        'maintenance' => 'ti-motorbike',
        'maintenance_overview' => 'ti-motorbike',
        'cheques' => 'ti-file',
        'sims' => 'ti-device-sim',
        'sim_invoices' => 'ti-file-invoice',
        'sim_companies' => 'ti-building',
        'fuel_cards' => 'ti-gas-station',
        'fuel_card_list' => 'ti-gas-station',
        'fuel_data' => 'ti-gas-station',
        'fuel_companies' => 'ti-building',
        'rta_fines' => 'ti-file-alert',
        'rta_fines_unpaid' => 'ti-file-alert',
        'rta_fines_paid' => 'ti-file-check',
        'rta_fines_tickets' => 'ti-file-alert',
        'rta_saliks' => 'ti-cash',
        'inventory' => 'ti-package',
        'visa_expense' => 'ti-credit-card',
        'installments' => 'ti-calendar-dollar',
        'license_expense' => 'ti-steering-wheel',
        'legal_case' => 'ti-scale',
        'passport_handover' => 'ti-e-passport',
        'expenses' => 'ti-cash',
        'vat' => 'ti-receipt-tax',
        'vat_ledger' => 'ti-receipt-tax',
        'vat_return_file' => 'ti-file-export',
        'leasing_companies' => 'ti-building',
        'leasing_companies_list' => 'ti-building',
        'leasing_invoices' => 'ti-file-invoice',
        'leasing_billing_invoice' => 'ti-file-plus',
        'leasing_receipt' => 'ti-file-plus',
        'leasing_payment' => 'ti-file-plus',
        'garages' => 'ti-parking',
        'garage_list' => 'ti-parking',
        'garage_customers' => 'ti-users',
        'supplier' => 'ti-truck',
        'suppliers' => 'ti-truck',
        'supplier_orders' => 'ti-truck',
        'supplier_invoices' => 'ti-truck',
        'supplier_payments' => 'ti-truck',
        'assets' => 'ti-box',
        'agreements' => 'ti-file-certificate',
        'documents' => 'ti-upload',
        'vouchers' => 'ti-ticket',
        'accounts' => 'ti-graph',
        'chart_of_accounts' => 'ti-settings',
        'ledger' => 'ti-settings',
        'user_management' => 'ti-users-group',
        'settings' => 'ti-adjustments',
        'erp_settings' => 'ti-adjustments',
    ],

    /*
    |--------------------------------------------------------------------------
    | Preset icons for the module settings picker (Tabler class without "ti ")
    |--------------------------------------------------------------------------
    */
    'presets' => [
        'ti-layout-dashboard' => 'Dashboard',
        'ti-building-bank' => 'Bank',
        'ti-user' => 'User',
        'ti-users' => 'Users',
        'ti-user-pin' => 'Rider',
        'ti-user-star' => 'Customer',
        'ti-user-plus' => 'Leads',
        'ti-motorbike' => 'Bike',
        'ti-device-sim' => 'SIM',
        'ti-gas-station' => 'Fuel',
        'ti-file-alert' => 'Alert / Fine',
        'ti-file-check' => 'Paid',
        'ti-cash' => 'Cash',
        'ti-receipt' => 'Receipt',
        'ti-receipt-tax' => 'VAT',
        'ti-credit-card' => 'Card',
        'ti-e-passport' => 'Passport',
        'ti-truck' => 'Truck',
        'ti-building' => 'Building',
        'ti-parking' => 'Parking',
        'ti-package' => 'Package',
        'ti-upload' => 'Upload',
        'ti-ticket' => 'Ticket',
        'ti-graph' => 'Chart',
        'ti-calendar-check' => 'Calendar',
        'ti-notes' => 'Notes',
        'ti-file' => 'File',
        'ti-box' => 'Box',
        'ti-settings' => 'Settings',
        'ti-adjustments-alt' => 'Generic',
    ],

    'max_upload_kb' => 512,
    'allowed_mimes' => ['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg'],

    /*
    |--------------------------------------------------------------------------
    | Online icon library (Tabler Icons via jsDelivr catalog)
    |--------------------------------------------------------------------------
    */
    'library' => [
        'provider' => 'tabler',
        'provider_label' => 'Tabler Icons',
        'provider_url' => 'https://tabler.io/icons',
        'cdn_icons_json' => 'https://cdn.jsdelivr.net/npm/@tabler/icons@3.28.1/icons.json',
        'search_limit' => 96,
    ],
];
